services:
  rosys:
    build: .
    network_mode: host
    privileged: true
    ports:
      - "8003:8003"
    volumes:
      - ./:/app
    hostname: docker
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
