services:
  zed_ros2:
    build: .
    # network_mode: host # Required for ROS2 discovery
    privileged: true # Needed for camera access
    runtime: nvidia # Needed for ZED SDK
    environment:
      - ROS_DOMAIN_ID=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ZED_GMSL2_CAMERA=1
      - ZED_GMSL_CAMERA=1
      - ZED_GMSL_CAMERA_MODE=0
      - ZED_GMSL_CAMERA_RESOLUTION=1080
      - ZED_GMSL_CAMERA_FPS=30
      - ZED_SDK_VERBOSE=1
    volumes:
      - /dev:/dev
      - /tmp:/tmp
      - /var/nvidia/nvcam/settings/:/var/nvidia/nvcam/settings
      - /usr/local/zed/settings:/usr/local/zed/settings
      - /usr/local/zed/resources:/usr/local/zed/resources #without this, the AI models do not get optimized -> Elaborate!
      # - /etc/systemd/system/zed_x_daemon.service:/etc/systemd/system/zed_x_daemon.service
      # - /sys/bus/i2c/devices:/sys/bus/i2c/devices
      # - /sys/class/video4linux:/sys/class/video4linux
    ports:
      - "9090:9090" # ROS bridge WebSocket port
    # tty: true # Keep STDIN open
    # stdin_open: true # Keep container running
    restart: unless-stopped
