version: "3.9"
services:
  rosys:
    image: "zauberzeug/rosys:latest"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ./../..:/rosys  # to directly modify rosys code
      - ./:/rosys/examples/zedxmini  # for developing within rosys workspace
    hostname: docker
    restart: unless-stopped 