# https://github.com/stereolabs/zed-ros2-wrapper/tree/master/docker
# https://github.dev/husarion/zed-docker/blob/ros2/Dockerfile.jetson

# Avalible dustynv ros humble images:
# 36.3.0 for Jetpack 6, 35.4.1 for Jetpack 5, 32.7.1 for Jetpack 4

# Based on https://hub.docker.com/r/stereolabs/zed/
# needed ubuntu 22.04 for jetson 6.0    
ARG L4T_MAJOR=36
ARG L4T_MINOR=3
ARG ZED_SDK_MAJOR=4
ARG ZED_SDK_MINOR=2
ARG ROS_DISTRO=noetic

### ROS CORE BUILD IMAGE ###
FROM stereolabs/zed:${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-devel-l4t-r${L4T_MAJOR}.${L4T_MINOR} AS ros-core-build

ARG ROS_DISTRO
SHELL ["/bin/bash", "-c"]

ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}compute,video,utility

# Basic dependencies
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository universe && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        python3-pip \
        python3-yaml \
        python3-dev \
        python3-venv \
        libtinyxml2-dev \
        libeigen3-dev \
        libboost-all-dev \
        libconsole-bridge-dev \
        liburdfdom-dev \
        libtinyxml-dev \
        liblog4cxx-dev \
        libpoco-dev \
        liblz4-dev \
        libgtest-dev \
        libssl-dev \
        libxml2-dev \
        pkg-config \
        curl && \
    rm -rf /var/lib/apt/lists/*

# Python dependencies via pip in a virtual environment
RUN python3 -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    python3 -m pip install -U pip && \
    pip3 install -U \
        'setuptools<58.0.0' \
        wheel && \
    pip3 install \
        rosdep==0.22.2 \
        rosinstall_generator==0.1.22 \
        vcstool==0.3.0 \
        catkin_tools==0.9.0 \
        'empy<4.0.0' \
        'catkin-pkg<1.0.0' \
        rospkg==1.5.0 \
        'numpy<1.24.0' \
        defusedxml==0.7.1 \
        netifaces

ENV PATH="/opt/venv/bin:$PATH"

# Setup ROS core workspace
WORKDIR /ros_ws
RUN mkdir -p src/ros_core && cd src/ros_core && \
    git clone https://github.com/ros/actionlib.git -b 1.14.0 && \
    git clone https://github.com/ros/bond_core.git -b 1.8.6 && \
    git clone https://github.com/ros/catkin.git -b 0.8.10 && \
    git clone https://github.com/ros/class_loader.git -b 0.5.0 && \
    git clone https://github.com/ros/cmake_modules.git -b 0.5.0 && \
    git clone https://github.com/ros/common_msgs.git -b 1.13.1 && \
    git clone https://github.com/ros/dynamic_reconfigure.git -b 1.7.3 && \
    git clone https://github.com/ros/gencpp.git -b 0.7.0 && \
    git clone https://github.com/jsk-ros-pkg/geneus.git -b 3.0.0 && \
    git clone https://github.com/ros/genlisp.git -b 0.4.18 && \
    git clone https://github.com/ros/genmsg.git -b 0.6.0 && \
    git clone https://github.com/RethinkRobotics-opensource/gennodejs.git -b 2.0.1 && \
    git clone https://github.com/ros/genpy.git -b 0.6.16 && \
    git clone https://github.com/ros/message_generation.git -b 0.4.1 && \
    git clone https://github.com/ros/message_runtime.git -b 0.4.13 && \
    git clone https://github.com/ros/nodelet_core.git -b 1.10.2 && \
    git clone https://github.com/ros/pluginlib.git -b 1.13.0 && \
    git clone https://github.com/ros/ros.git -b 1.15.8 && \
    git clone https://github.com/ros/ros_comm.git -b 1.16.0 && \
    git clone https://github.com/ros/ros_comm_msgs.git -b 1.11.3 && \
    git clone https://github.com/ros/ros_environment.git -b 1.3.2 && \
    git clone https://github.com/ros/rosbag_migration_rule.git -b 1.0.1 && \
    git clone https://github.com/ros/rosconsole.git -b 1.14.3 && \
    git clone https://github.com/ros/rosconsole_bridge.git -b 0.5.4 && \
    git clone https://github.com/ros/roscpp_core.git -b 0.7.2 && \
    git clone https://github.com/ros/roslisp.git -b 1.9.25 && \
    git clone https://github.com/ros/rospack.git -b 2.6.2 && \
    git clone https://github.com/ros/std_msgs.git -b 0.5.13

# Build ROS core
RUN cd /ros_ws && \
    rosdep init && \
    rosdep update && \
    catkin config --install && \
    catkin build -DCMAKE_BUILD_TYPE=Release

### ZED BUILD IMAGE ###
FROM ros-core-build AS zed-build

# scope to build 
ARG L4T_MAJOR
ARG L4T_MINOR
ARG ZED_SDK_MAJOR
ARG ZED_SDK_MINOR
ARG ROS_DISTRO

# Copy ROS install from core build
COPY --from=ros-core-build /ros_ws/install /opt/ros/${ROS_DISTRO}

# Setup ZED workspace
WORKDIR /ros_ws
RUN rm -rf * && \
    git clone --recursive https://github.com/stereolabs/zed-ros-wrapper src/zed-ros-wrapper && \
    git clone --recursive https://github.com/foxglove/ros-foxglove-bridge src/ros-foxglove-bridge && \
    source /opt/ros/$ROS_DISTRO/setup.bash && \
    rosdep install --from-paths src -y -i && \
    catkin_make -DCMAKE_BUILD_TYPE=Release


### RUN IMAGE ###
FROM stereolabs/zed:${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-runtime-l4t-r${L4T_MAJOR}.${L4T_MINOR} AS run

# scope to run
ARG L4T_MAJOR
ARG L4T_MINOR
ARG ZED_SDK_MAJOR
ARG ZED_SDK_MINOR
ARG ROS_DISTRO
SHELL ["/bin/bash", "-c"]

ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}compute,video,utility

# Install basic dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-pip \
        python3-yaml \
        python3-venv \
        curl && \
    rm -rf /var/lib/apt/lists/*

# Setup Python virtual environment
RUN python3 -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip3 install -U \
        rosdep==0.22.2 \
        'numpy<1.24.0'

ENV PATH="/opt/venv/bin:$PATH"

# Copy ROS and workspace from build
COPY --from=ros-core-build /opt/ros/${ROS_DISTRO} /opt/ros/${ROS_DISTRO}
COPY --from=zed-build /ros_ws /ros_ws

# Setup environment
ENV ROS_DISTRO=${ROS_DISTRO}
RUN . /opt/venv/bin/activate && \
    rosdep init && \
    rosdep update

COPY ros_entrypoint_jetson.sh /ros_entrypoint.sh
COPY launch.sh /launch.sh
RUN chmod 755 /ros_entrypoint.sh && \
    chmod 755 /launch.sh

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["/launch.sh"]